YMart/YMart/ViewModels/Brochure/AddBrochureViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace YMart.ViewModels.Brochure
{
    using YMart.Data.Models;
    public class AddBrochureViewModel
    {
        [Required]
        public string ImageURL { get; set; }

        public List<string> ProductNames { get; set; }

    }
}

YMart/YMart/ViewModels/Brochure/BasicBrochureViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace YMart.ViewModels.Brochure
{
    public class BasicBrochureViewModel
    {
        [Required]
        public string ImageURL { get; set; }

        public List<string> ProductNames { get; set; }

        [Required]
        public Guid Id { get; set; }

        public bool IsActive { get; set; }
    }
}

YMart/YMart/ViewModels/Brochure/DeleteBrochureViewModel.cs
namespace YMart.ViewModels.Brochure
{
    public class DeleteBrochureViewModel
    {
        public Guid Id { get; set; }
    }
}

YMart/YMart/ViewModels/Brochure/EditBrochureViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace YMart.ViewModels.Brochure
{
    public class EditBrochureViewModel
    {

        [Required]
        public Guid Id { get; set; }

        [Required]
        public string ImageURL { get; set; }

        public List<string> ProductNames { get; set; }

        public List<string> AllProducts {  get; set; }

        public bool IsActive { get; set; }
    }
}

YMart/YMart/Controllers/BrochureController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YMart.Data;
using YMart.Data.Models;
using YMart.ViewModels.Brochure;

namespace YMart.Controllers
{
    public class BrochureController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public BrochureController(ApplicationDbContext context)
        {
            dbContext = context;
        }

        [HttpGet]
        public async Task<IActionResult> AddBrochure()
        {
            ViewData["ProductNamesList"] = await dbContext.Products.Where(p => p.IsDeleted == false).Select(p => p.Name).ToListAsync();
            var model = new AddBrochureViewModel();
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddBrochure(AddBrochureViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            Brochure brochure = new Brochure
            {
                ImageURL = model.ImageURL,
                ProductNames = await dbContext.Products.Where(p => p.IsDeleted == false && model.ProductNames.Contains(p.Name)).Select(pn => pn.Name).ToListAsync(),
                IsActive = true
            };

            await dbContext.Brochure.AddAsync(brochure);
            await dbContext.SaveChangesAsync();

            return this.RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> BrochureList()
        {
            var model = await dbContext.Brochure.Select(b => new BasicBrochureViewModel()
            {
                Id = b.Id,
                ImageURL = b.ImageURL,
                ProductNames = b.ProductNames,
                IsActive = b.IsActive
            }).ToListAsync();

            return this.View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Manage(Guid id)
        {
            var model = await dbContext.Brochure.Where(b => b.Id == id).AsNoTracking().Select(b => new BasicBrochureViewModel
            {
                Id = b.Id,
                ImageURL = b.ImageURL,
                ProductNames = b.ProductNames,
                IsActive = b.IsActive
            }).FirstOrDefaultAsync();


            return this.View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = await dbContext.Brochure.Where(b => b.Id == id).AsNoTracking().Select(b => new EditBrochureViewModel
            {
                Id = b.Id,
                ImageURL = b.ImageURL,
                ProductNames = b.ProductNames,
                AllProducts = dbContext.Products.Where(p => p.IsDeleted == false).Select(p => p.Name).ToList(),
                IsActive = b.IsActive
            }).FirstOrDefaultAsync();


            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditBrochureViewModel model, Guid id)
        {
            if (!this.ModelState.IsValid)
            {
             model.AllProducts = await dbContext.Products
            .Where(p => p.IsDeleted == false)
            .Select(p => p.Name)
            .ToListAsync();

                //return this.View(model);
            }

            Brochure? entity = await dbContext.Brochure.FindAsync(id);

            if (entity == null)
            {
                throw new ArgumentException("Invalid id");
            }

            //entity.Id = id;
            entity.IsActive = model.IsActive;
            entity.ImageURL = model.ImageURL;
            entity.ProductNames = model.ProductNames;


            await this.dbContext.SaveChangesAsync();

            //return RedirectToAction("Index");
            return RedirectToAction("Manage", new { id = id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var model = await dbContext.Brochure.Where(b => b.Id == id).AsNoTracking().Select(b => new DeleteBrochureViewModel
            {
                Id = b.Id,
            }).FirstOrDefaultAsync();

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteBrochureViewModel model)
        {
            Brochure? brochure = await dbContext.Brochure.Where(p => p.Id == model.Id).FirstOrDefaultAsync();

            if (brochure != null)
            {

                dbContext.Brochure.Remove(brochure);

                await dbContext.SaveChangesAsync();
            }

            return this.RedirectToAction("BrochureList");
        }
    }
}

YMart/YMart/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using YMart.Data;
using YMart.Data.Models;
using YMart.ViewModels.Product;
using YMart.ViewModels.Order;
using static YMart.Constants.DataConstants;

namespace YMart.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public ProductController(ApplicationDbContext context)
        {
            this.dbContext = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index(List<string> CategoryFilters, List<string> productNames,string searchTextName)
        {
            ViewData["CategoryFilters"] = CategoryFilters;
            ViewData["SearchTextName"] = searchTextName;

            var query = dbContext.Products.Where(p => p.IsDeleted == false);

            if (productNames != null && productNames.Any())
            {
                query = query.Where(p => productNames.Contains(p.Name));
            }

            if (CategoryFilters != null && CategoryFilters.Any())
            {
                query = query.Where(p => CategoryFilters.Contains(p.Category));
            }

            if (!string.IsNullOrWhiteSpace(searchTextName))
            {
                //query = query.Where(e => e.Name.Contains(searchTextName, StringComparison.OrdinalIgnoreCase));
                var lowerSearch = searchTextName.ToLower();
                query = query.Where(e => e.Name.ToLower().Contains(lowerSearch));
            }

            var model = await query
                    .Select(p => new BasicProductViewModel()
                    {
                        Id = p.Id,
                        ImageURL = p.ImageURL,
                        Name = p.Name,
                        Price = p.Price,
                        DiscountedPrice = p.DiscountedPrice,
                        DiscountPercentage = p.DiscountPercentage,
                        Quantity = p.Quantity,
                        Category = p.Category
                    }).AsNoTracking().ToListAsync();

            return this.View(model);           
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new AddProductViewModel();
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddProductViewModel model)
        {
            if (!this.ModelState.IsValid)
            {               
                return this.View(model);
            }

                  
            if (model.Price < MinPrice || model.Price > MaxPrice)
            {
                ModelState.AddModelError(nameof(model.Price), $"Price must be between {MinPrice}€ and {MaxPrice}€");             
                return this.View(model);
            }

            Product product = new Product
            {
                Name = model.Name,
                Description = model.Description,
                Price = model.Price,
                DiscountPercentage = model.DiscountPercentage,
                IsOnSale = model.IsOnSale,
                ImageURL = model.ImageURL,
                Category = model.Category,
                Quantity = model.Quantity
            };

            await dbContext.Products.AddAsync(product);
            await dbContext.SaveChangesAsync();

            return this.RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var model = await dbContext.Products.Where(p => p.Id == id).Where(p => p.IsDeleted == false).AsNoTracking().Select(p => new DetailedProductViewModel
            {
                Id = p.Id,
                Description = p.Description,
                Category = p.Category,
                ImageURL = p.ImageURL,                
                Name = p.Name,               
                Price = p.Price,
                DiscountedPrice = p.DiscountedPrice,
                DiscountPercentage = p.DiscountPercentage,
                Quantity= p.Quantity,              
            }).FirstOrDefaultAsync();


            return this.View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = await dbContext.Products.Where(p => p.Id == id).Where(p => p.IsDeleted == false).AsNoTracking().Select(p => new EditProductViewModel
            {
                Name = p.Name,
                Description = p.Description,
                Price = p.Price,
                ImageURL = p.ImageURL,
                Category = p.Category,
                Quantity = p.Quantity,
                IsOnSale = p.IsOnSale,
                DiscountPercentage = p.DiscountPercentage,
            }).FirstOrDefaultAsync();

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditProductViewModel model, Guid id)
        {
            if (!this.ModelState.IsValid)
            {             
                return this.View(model);
            }
           
            if (model.Price < MinPrice || model.Price > MaxPrice)
            {
                ModelState.AddModelError(nameof(model.Price), $"Price must be between {MinPrice}€ and {MaxPrice}€");

                return this.View(model);
            }

            if (model.DiscountPercentage < 0 || model.DiscountPercentage > 100)
            {
                ModelState.AddModelError(nameof(model.DiscountPercentage), $"Discount Percentage must be between {0}% and {100}%");

                return this.View(model);
            }

            Product? entity = await dbContext.Products.FindAsync(id);

            if (entity == null || entity.IsDeleted)
            {
                throw new ArgumentException("Invalid id");
            }

            //entity.Id = id;
            entity.Name = model.Name;
            entity.Description = model.Description;
            entity.Price = model.Price;
            entity.ImageURL = model.ImageURL;            
            entity.Category = model.Category;
            entity.Quantity = model.Quantity;
            entity.IsOnSale = model.IsOnSale;
            entity.DiscountPercentage = model.DiscountPercentage;

            await this.dbContext.SaveChangesAsync();

            //return RedirectToAction("Index");
            return RedirectToAction("Details", new { id = id });
        }


        [HttpGet]
        public async Task<IActionResult> SoftDelete(Guid id)
        {
            var model = await dbContext.Products.Where(p => p.Id == id).Where(p => p.IsDeleted == false).AsNoTracking().Select(p => new DeleteProductViewModel
            {
                Id = p.Id,
                Name = p.Name
            }).FirstOrDefaultAsync();

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SoftDelete(DeleteProductViewModel model)
        {
            Product? product = await dbContext.Products.Where(p => p.Id == model.Id).Where(p => p.IsDeleted == false).FirstOrDefaultAsync();

            if (product != null)
            {

                product.IsDeleted = true;

                await dbContext.SaveChangesAsync();
            }

            return this.RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> HardDelete(Guid id)
        {
            var model = await dbContext.Products.Where(p => p.Id == id).Where(p => p.IsDeleted == false).AsNoTracking().Select(p => new DeleteProductViewModel
            {
                Id = p.Id,
                Name = p.Name
            }).FirstOrDefaultAsync();

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> HardDelete(DeleteProductViewModel model)
        {
            Product? product = await dbContext.Products.Where(p => p.Id == model.Id).FirstOrDefaultAsync();

            if (product != null)
            {

                dbContext.Products.Remove(product);

                await dbContext.SaveChangesAsync();
            }

            return this.RedirectToAction("Index");
        }
        
    }
}

YMart/YMart/Views/Brochure/AddBrochure.cshtml
@using YMart.ViewModels.Brochure;
@model AddBrochureViewModel
@{
    List<string> ProductNamesList = ViewData["ProductNamesList"] as List<string> ?? new List<string>();
    ViewData["Title"] = "Add Brochure";
}

<div class="d-flex justify-content-between align-items-center mb-3" style="margin-top: 20px;">
    @if (User.IsInRole("Administrator"))
    {
        <h2>@ViewData["Title"]</h2>
    }
    @if (!User.IsInRole("Administrator"))
    {
        <h2>Can only be viewed by Administrators</h2>
    }
</div>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        @if (User.IsInRole("Administrator"))
        {
            <form asp-action="AddBrochure" method="post" enctype="multipart/form-data">
                <div class="mb-2">
                    <label asp-for="@Model.ImageURL" class="form-label-add-edit">ImageURL</label>
                    <input asp-for="@Model.ImageURL" class="form-control" aria-required="false" placeholder="Enter image URL" />
                    <span asp-validation-for="@Model.ImageURL" class="text-danger"></span>
                </div>

                <div class="row">
                    <div class="col-sm-6 mb-2">
                        <label class="form-label-add-edit">Products</label>
                        <div>
                            @foreach (var productName in ProductNamesList)
                            {
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="ProductNames" value="@productName" id="@productName" />
                                    <label class="form-check-label" for="@productName">@productName</label>
                                </div>
                            }
                        </div>
                    </div>
                </div>

                <div class="mb-2">
                    <input class="btn btn-warning btn-dark-text w-100 py-2 fw-bold rounded" type="submit" value="Save" />
                </div>
            </form>
        }
    </div>
</div>

YMart/YMart/Views/Brochure/BrochureList.cshtml
@using YMart.ViewModels.Brochure;
@model IEnumerable<BasicBrochureViewModel>

@{
    ViewData["Title"] = "Brochures";
}
<div class="d-flex justify-content-between align-items-center mb-3" style="margin-top: 20px;">
    @if (User.IsInRole("Administrator"))
    {
        <h2>@ViewData["Title"]</h2>
    }
    @if (!User.IsInRole("Administrator"))
    {
        <h2>Can only be viewed by Administrators</h2>
    }
</div>
<hr />

 @if (User.IsInRole("Administrator"))
{
    <div class="d-flex justify-content-between align-items-center mb-3" style="margin-top: 20px;">      
            <a asp-controller="Brochure" asp-action="AddBrochure" class="btn btn-primary"><i class="bi bi-plus-circle"></i>Add Brochure</a>
    </div>
    <hr />

    <div style="display: flex; flex-direction: column; gap: 20px; margin-top: 20px;">
        @foreach (var brochure in Model)
        {
            <form asp-controller="Product" asp-action="Index" method="get">
                @foreach (var name in brochure.ProductNames)
                {
                    <input type="hidden" name="productNames" value="@name" />
                }
                <input type="image" src="@brochure.ImageURL" alt="Brochure Image" style="width:1296px; height:350px;" />
            </form>
            <a asp-controller="Brochure" asp-action="Manage" asp-route-id="@brochure.Id" class="btn btn-info">Manage</a>
        }
    </div>
}

YMart/YMart/Views/Brochure/Delete.cshtml
@using YMart.ViewModels.Brochure;
@model DeleteBrochureViewModel

@{
    ViewData["Title"] = " Delete Brochure";
    var today = DateTime.Now.ToString("dd-MM-yyyy");
}

<div class="d-flex justify-content-between align-items-center mb-3" style="margin-top: 20px;">
    @if (User.IsInRole("Administrator"))
    {
        <h2>@ViewData["Title"]</h2>
    }
    @if (!User.IsInRole("Administrator"))
    {
        <h2>Can only be viewed by Administrators</h2>
    }
</div>
<hr />

<div class="row justify-content-center">
    <div class="col-md-6">
        @if (User.IsInRole("Administrator"))
        {
            <div class="card">
                <div class="card-body">                  
                    <p class="text-danger mt-3">Are you sure you want to delete this brochure?</p>
                </div>
                <div class="card-footer">
                    <form asp-controller="Brochure" asp-action="Delete" method="post">
                        <input type="hidden" asp-for="Id" />
                        <button type="submit" class="btn btn-danger">Confirm Delete</button>
                        <button type="button" onclick="history.back()" class="User-Buttons" id="yellow"><i class="bi bi-arrow-bar-left"></i>Back</button>
                    </form>
                </div>
            </div>
        }
    </div>
</div>

YMart/YMart/Views/Brochure/Edit.cshtml
@using YMart.ViewModels.Brochure;
@model EditBrochureViewModel
@{
    ViewData["Title"] = "Edit Brochure";
}

<div class="d-flex justify-content-between align-items-center mb-3" style="margin-top: 20px;">
    @if (User.IsInRole("Administrator"))
    {
        <h2>@ViewData["Title"]</h2>
    }
    @if (!User.IsInRole("Administrator"))
    {
        <h2>Can only be viewed by Administrators</h2>
    }
</div>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        @if (User.IsInRole("Administrator"))
        {
            <form asp-action="Edit" method="post" enctype="multipart/form-data">
                <div class="mb-2">
                    <label asp-for="@Model.ImageURL" class="form-label-add-edit">ImageURL</label>
                    <input asp-for="@Model.ImageURL" class="form-control" aria-required="false" placeholder="Enter image URL" />
                    <span asp-validation-for="@Model.ImageURL" class="text-danger"></span>
                </div>

                <div class="row">
                    <div class="col-sm-6 mb-2">
                        <div class="col-sm-6 mb-2">
                            <label asp-for="IsActive" class="form-label-add-edit">Brochure is active status</label>
                            <select asp-for="IsActive" class="form-select" aria-required="true">
                                <option value="">Choose if a brochure is active or not</option>
                                <option value="True" Model.IsActive="True">True</option>
                                <option value="False" Model.IsActive="False">False</option>
                            </select>
                            <span asp-validation-for="IsActive" class="text-danger"></span>
                        </div>
                        <label class="form-label-add-edit">Products</label>
                        <div>
                            @foreach (var productName in @Model.AllProducts)
                            {
                                <div class="form-check">
                                    @if (@Model.ProductNames.Contains(productName))
                                    {
                                        <input class="form-check-input" type="checkbox" name="ProductNames" value="@productName" id="@productName" checked/>
                                    }
                                    else
                                    {
                                        <input class="form-check-input" type="checkbox" name="ProductNames" value="@productName" id="@productName"/>
                                    }
                                    <label class="form-check-label" for="@productName">@productName</label>
                                </div>
                            }
                        </div>
                    </div>
                </div>

                <div class="mb-2">
                    <input class="btn btn-warning btn-dark-text w-100 py-2 fw-bold rounded" type="submit" value="Save" />
                </div>
            </form>
        }
    </div>
</div>

YMart/YMart/Views/Brochure/Manage.cshtml
@using YMart.ViewModels.Brochure;
@model BasicBrochureViewModel

<div class="d-flex justify-content-between align-items-center mb-3" style="margin-top: 20px;">
    @if (User.IsInRole("Administrator"))
    {
        <h2>@ViewData["Title"]</h2>
    }
    @if (!User.IsInRole("Administrator"))
    {
        <h2>Can only be viewed by Administrators</h2>
    }
</div>
<hr />

@if (User.IsInRole("Administrator"))
{
<link rel="stylesheet" href="~/css/style.css" />
<style>
    .card-footer {
        border-bottom: 1px solid rgba(0,0,0,.125);
        border-radius: 0.25rem;
    }

    .row {
        display: flex;
        gap: 3rem;
    }

    #dp-text {
        color: red;
        margin-bottom: 0.5rem;
    }

    body {
        background-image: url('/images/stylized_white_2.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style>

<div class="row justify-content-center" style="margin: 0 auto; margin-top:50px;">
    <div class="col-md-4 text-center" style="width:800px; height:230px;">
        @if (!string.IsNullOrEmpty(Model.ImageURL))
        {
            <img src="@Model.ImageURL" class="img-fluid" style="width: 770px; height:200px; object-fit:contain;" />
        }
        else
        {
            <img src="~/img/no-image-available-02.jpg" class="img-fluid" style="max-width: 100%; height: 100%;" alt="No Image Available" />
        }
    </div>

    <div class="col-md-8" style="max-width:650px;">
        <div class="card-body">
            <h4>Products in Brochure</h4>
            @foreach(var productName in @Model.ProductNames)
            {
            <h5 class="card-title">@productName</h5>
            <hr />
            }
            <h6 class="card-subtitle">Is Active: @Model.IsActive</h6>
            <hr />
        </div>
        <br />
        @if (User.IsInRole("Administrator"))
        {
            <div>
                <a asp-controller="Brochure" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary d-flex justify-content-center align-items-center flex-fill mx-1">Edit</a>
                <a asp-controller="Brochure" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger d-flex justify-content-center align-items-center flex-fill mx-1" onclick="return confirm('Are you sure you want to delete this brochure forever?');"><i class="bi bi-trash"></i>Delete</a>
            </div>
        }
    </div>
</div>
}